apiVersion: batch/v1
kind: CronJob
metadata:
  name: ds
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: domain-scarper
            image: domain-scraper
            # command: [ "sleep", "3600" ]
            command: [ "domain-scraper" ]
            volumeMounts:
              - mountPath: /domain-scraper/emails
                name: emails-volume
            imagePullPolicy: Never
          restartPolicy: Never
          volumes:
          - name: emails-volume
            hostPath:
              path: /hosthome/domain-scraper-workdir/emails
