apiVersion: batch/v1
kind: CronJob
metadata:
  name: ds
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: domain-scarper
            image: domain-scraper
            command: [ "domain-scraper" ]
            # paths defined below are relative to mounted emails-volume
            env:
              - name: INPUT_DIR
                value: "emails/input"
              - name: ARCHIVE_DIR
                value: "emails/archieve"
              - name: DB_FILE
                value: "db/email_database.json"
            envFrom:
              - secretRef:
                  name: email-secrets
            volumeMounts:
              - mountPath: /domain-scraper/emails
                name: emails-volume
            imagePullPolicy: Never
          restartPolicy: Never
          volumes:
          - name: emails-volume
            hostPath:
              path: /hosthome/domain-scraper-workdir/emails
